"""Add tts_demo_used to User

Revision ID: 054e4e52a850
Revises: ade16ed0a2fe
Create Date: 2025-06-25 09:55:25.470962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054e4e52a850'
down_revision: Union[str, Sequence[str], None] = 'ade16ed0a2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tts_demo_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tts_demo_used')
    # ### end Alembic commands ###
